apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: izkyeml48-nodejs 
  janus-idp.io/tekton: izkyeml48-nodejs
  backstage.io/kubernetes-id: izkyeml48-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: izkyeml48-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  